services:
  # Nginx Webserver
  nginx:
    image: nginx:alpine
    container_name: nginx-webserver
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - backend
    restart: unless-stopped

  # Squid Reverse Proxy
  squid:
    image: ubuntu/squid:latest
    container_name: squid-proxy
    ports:
      - "3128:3128"
      - "80:80"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf:ro
    networks:
      - backend
      - frontend
    depends_on:
      - nginx
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

volumes:
  squid_logs:
    driver: local